// <auto-generated />
using CampaignDesignerBE.Data;
using CampaignDesignerBE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace campaignDesignerBE.Migrations
{
    [DbContext(typeof(CampaignDesignerContext))]
    [Migration("20180309023733_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CampaignDesignerBE.Models.Campaign", b =>
                {
                    b.Property<int>("CampaignID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CampaignName");

                    b.HasKey("CampaignID");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CampaignDesignerBE.Models.PlotPoint", b =>
                {
                    b.Property<int>("PlotPointID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CampaignID");

                    b.Property<string>("PlotPointDesc");

                    b.Property<bool>("isRoot");

                    b.HasKey("PlotPointID");

                    b.ToTable("PlotPoints");
                });

            modelBuilder.Entity("CampaignDesignerBE.Models.Transition", b =>
                {
                    b.Property<int>("TransitionID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityType");

                    b.Property<int>("InputID");

                    b.Property<int>("OutputID");

                    b.Property<int?>("PlotPointID");

                    b.Property<string>("TransitionSummary");

                    b.HasKey("TransitionID");

                    b.HasIndex("PlotPointID");

                    b.ToTable("Transitions");
                });

            modelBuilder.Entity("CampaignDesignerBE.Models.Transition", b =>
                {
                    b.HasOne("CampaignDesignerBE.Models.PlotPoint")
                        .WithMany("Transitions")
                        .HasForeignKey("PlotPointID");
                });
#pragma warning restore 612, 618
        }
    }
}
